### ISSUE TITLE
Are ouput precursor m/z values already deisotoped?

### ISSUE THREAD

**Issue by irleader** [ctarn/PepPre.jl#2]
Hi,

I am wondering if the output precursor m/z values from PepPre are already monoisotopic m/z after deisotoping the raw m/z? 
Such that I do not have to add or minus the mass of a proton on the value to consider other possibilities?

for example, I use fold of 4 to get 4 possible m/z and charge for a MS/MS spectrum, they are:
679.321 and 4+
679.067 and 4+
677.382 and 1+
677.712 and 1+

Do I have to consider the following as possible precursor m/z values?
679.321 + mass of proton, 679.321 - mass of proton
679.067 + mass of proton, 679.067 - mass of proton 
677.382 + mass of proton, 677.382 - mass of proton
677.712 + mass of proton, 677.712 - mass of proton

Thanks!

**Comment by ctarn** [comment]
Hi! Yes. The exported values are m/z values of estimated monoisotopic peaks of precursors, and thus it is not suggested to further add or minus mass of protons.

**Comment by irleader** [comment]
Thanks  a lot for your prompt answer!
